"""Plan-task reviewer quorum validation (Phase 3.1).

`plan_task` uses reviewer-slot coordination (REVISE_PLAN at >=2 FAILs).
Operators may deliberately configure the same model in several slots for
single-provider / same-model sampling; the guard now only requires at least
two configured slots before expensive prompt assembly.
"""

from __future__ import annotations

import asyncio
import pathlib
import unittest
from unittest.mock import MagicMock, patch


def _make_ctx() -> MagicMock:
    ctx = MagicMock()
    ctx.repo_dir = pathlib.Path(".")
    ctx.drive_root = pathlib.Path(".")
    ctx.emit_progress_fn = MagicMock()
    return ctx


class TestPlanReviewerQuorum(unittest.IsolatedAsyncioTestCase):
    """Cover the three contract cases spelled out in the task:

    * 1 model → error
    * duplicates (e.g. ["a", "a", "b"]) → proceeds as explicit slots
    * 2+ slots ([a, b, c] or [a, a, a]) → proceeds past the quorum gate
    """

    async def _run_with_models(self, models, env_raw=None):
        """Invoke `_run_plan_review_async` with injected user-configured
        reviewer list. Patches BOTH `_cfg.get_review_models` (resolved count)
        AND the `OUROBOROS_REVIEW_MODELS` env var (raw user intent for the
        duplicate check) so both quorum branches see consistent data.

        `env_raw` defaults to the comma-joined `models` — the common case
        where resolved and raw match. Pass `env_raw=""` or a different CSV
        to exercise the direct-provider-fallback scenario where the resolved
        list is generated by `config.get_review_models` (not user-authored)
        and the duplicate check must skip.
        """
        import os as _os
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()
        raw_value = env_raw if env_raw is not None else ",".join(models)

        with (
            patch.dict(_os.environ, {"OUROBOROS_REVIEW_MODELS": raw_value}, clear=False),
            patch.object(_cfg, "get_review_models", return_value=list(models)),
            patch.object(pr, "_get_review_models", return_value=list(models)),
            # Stub the prompt-building dependencies so we don't need a real
            # repo layout for the quorum check. The quorum gate fires BEFORE
            # the prompt is assembled; the patches here are only defensive
            # so tests do not touch the disk if the gate ever moves.
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            return await pr._run_plan_review_async(ctx, "plan", "goal", [])

    async def test_single_model_returns_error(self):
        result = await self._run_with_models(["only/one"])
        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("at least 2 reviewer slots", result)
        self.assertIn("OUROBOROS_REVIEW_MODELS", result)

    async def test_duplicates_in_list_proceed_as_explicit_slots(self):
        """User-authored duplicates are valid reviewer slots."""
        result = await self._run_with_models(
            ["a", "a", "b"], env_raw="a,a,b",
        )
        self.assertNotIn("duplicate reviewer models", result)
        self.assertNotIn("at least 2 reviewer slots", result)

    async def test_two_unique_models_no_duplicates_proceeds(self):
        result = await self._run_with_models(["a", "b"])
        # Must NOT return the quorum error; the call reaches the reviewer-
        # aggregation path (stubbed) and produces the standard output.
        self.assertNotIn("at least 2 unique", result)
        self.assertNotIn("duplicate reviewer models", result)

    async def test_three_unique_models_proceeds(self):
        """The default shipped config (3 distinct OpenRouter models) must pass."""
        result = await self._run_with_models([
            "openai/gpt-5.5",
            "google/gemini-3.1-pro-preview",
            "anthropic/claude-opus-4.6",
        ])
        self.assertNotIn("at least 2 unique", result)
        self.assertNotIn("duplicate reviewer models", result)

    async def test_all_same_model_three_times_returns_error(self):
        """All-identical reviewer slots are allowed for same-model sampling."""
        result = await self._run_with_models(
            ["x", "x", "x"], env_raw="x,x,x",
        )
        self.assertNotIn("duplicate reviewer models", result)
        self.assertNotIn("at least 2 reviewer slots", result)

    async def test_mixed_duplicates_proceed(self):
        """Duplicate reviewer slots preserve user intent and ordering."""
        result = await self._run_with_models(
            ["c", "b", "a", "b", "c"], env_raw="c,b,a,b,c",
        )
        self.assertNotIn("duplicate reviewer models", result)


class TestQuorumGateOrdering(unittest.IsolatedAsyncioTestCase):
    """The quorum gate must fire BEFORE expensive work (prompt assembly,
    repo pack build, estimate_tokens). Otherwise the error comes late and
    we waste I/O on every mis-configured call."""

    async def test_gate_fires_before_prompt_assembly(self):
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()

        prompt_build_calls = {"n": 0}

        def _spy_pack(*args, **kwargs):
            prompt_build_calls["n"] += 1
            return ("pack", [])

        with (
            # User configured only 1 model → quorum gate must fire.
            patch.object(_cfg, "get_review_models", return_value=["x"]),
            patch.object(pr, "_get_review_models", return_value=["x", "x", "x"]),
            patch.object(pr, "build_full_repo_pack", side_effect=_spy_pack),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertTrue(result.startswith("ERROR"))
        self.assertEqual(
            prompt_build_calls["n"], 0,
            "repo-pack build ran despite the quorum gate firing — expensive work "
            "should never happen when models are misconfigured",
        )


class TestDuplicateSlotsInActualRun(unittest.IsolatedAsyncioTestCase):
    """After the quorum gate passes, the parallel run preserves reviewer slots.

    Duplicate model IDs are intentional for same-model sampling; the runtime
    must not dedupe them away before launching reviewers.
    """

    async def test_two_model_config_runs_two_slots(self):
        """`OUROBOROS_REVIEW_MODELS="a,b"` invokes exactly those two slots."""
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()
        call_log: list[str] = []

        def _spy_reviewer(ctx_inner, model, *args, **kwargs):
            call_log.append(model)
            return {
                "model": model, "text": "AGGREGATE: GREEN", "error": None,
                "tokens_in": 0, "tokens_out": 0,
            }

        with (
            patch.object(_cfg, "get_review_models",
                         return_value=["model/a", "model/b"]),
            patch.object(pr, "_get_review_models",
                         return_value=["model/a", "model/b"]),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(pr, "_query_reviewer", side_effect=_spy_reviewer),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        assert "ERROR" not in result or "Plan Review Results" in result, (
            f"Unexpected error path: {result[:300]}"
        )
        assert call_log == ["model/a", "model/b"], call_log

    async def test_three_unique_config_runs_three_reviewers(self):
        """3 unique configured reviewers → 3 unique invocations (no change)."""
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()
        call_log: list[str] = []

        def _spy_reviewer(ctx_inner, model, *args, **kwargs):
            call_log.append(model)
            return {
                "model": model, "text": "AGGREGATE: GREEN", "error": None,
                "tokens_in": 0, "tokens_out": 0,
            }

        with (
            patch.object(_cfg, "get_review_models",
                         return_value=["a", "b", "c"]),
            patch.object(pr, "_get_review_models",
                         return_value=["a", "b", "c"]),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(pr, "_query_reviewer", side_effect=_spy_reviewer),
        ):
            await pr._run_plan_review_async(ctx, "plan", "goal", [])

        assert call_log == ["a", "b", "c"], call_log


class TestQuorumWithRealEnvVar(unittest.IsolatedAsyncioTestCase):
    """Integration test that exercises the real `OUROBOROS_REVIEW_MODELS` env-var
    → `_get_review_models` → quorum-check chain without patching
    `_get_review_models`. Guards against the duplicate-slot quorum path
    rejecting valid two-slot configurations."""

    async def _run_with_env(self, models_env: str) -> str:
        """Run the full plan-review pipeline with `OUROBOROS_REVIEW_MODELS`
        set to the given CSV; downstream plumbing is stubbed but the
        `_get_review_models` path runs for real."""
        import os as _os
        from ouroboros.tools import plan_review as pr

        ctx = _make_ctx()

        with (
            patch.dict(_os.environ, {"OUROBOROS_REVIEW_MODELS": models_env}, clear=False),
            # Leave `_get_review_models` / `_cfg.get_review_models` unmocked so
            # the real parse + pad logic runs. Stub out prompt assembly and the
            # LLM call.
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            return await pr._run_plan_review_async(ctx, "plan", "goal", [])

    async def test_two_unique_env_models_pass_quorum_gate(self):
        """`OUROBOROS_REVIEW_MODELS="a,b"` is a valid two-slot review."""
        result = await self._run_with_env("openrouter/a,openrouter/b")
        # Must NOT hit the quorum error — user configured 2 reviewer slots.
        self.assertNotIn("at least 2 reviewer slots", result,
            f"two-slot env config was incorrectly rejected: {result[:500]}")
        self.assertNotIn("duplicate reviewer models", result,
            f"duplicate-slot branch rejected valid reviewer slots: {result[:500]}")

    async def test_three_unique_env_models_pass_quorum_gate(self):
        """Shipped default: 3 distinct OpenRouter models via env must pass."""
        result = await self._run_with_env(
            "openai/gpt-5.5,google/gemini-3.1-pro-preview,anthropic/claude-opus-4.6"
        )
        self.assertNotIn("at least 2 reviewer slots", result)
        self.assertNotIn("duplicate reviewer models", result)

    async def test_single_env_model_returns_error(self):
        """One raw configured slot is still a configuration error."""
        result = await self._run_with_env("only/one")
        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("at least 2 reviewer slots", result)
        self.assertIn("OUROBOROS_REVIEW_MODELS", result)

    async def test_user_authored_duplicates_in_env_proceed(self):
        """`OUROBOROS_REVIEW_MODELS="a,a,b"` is explicit same-model sampling."""
        result = await self._run_with_env("dup/x,dup/x,other/y")
        self.assertNotIn("duplicate reviewer models", result)
        self.assertNotIn("at least 2 reviewer slots", result)


class TestDirectProviderFallbackAccepted(unittest.IsolatedAsyncioTestCase):
    """When `config.get_review_models()` emits `[main, light, light]` as the
    direct-provider fallback (v4.39.0 quorum-safe shape), `_run_plan_review_async`
    MUST accept it — the duplicated `light` entries are server-generated,
    not user-authored, and the raw env var either points at a non-matching
    OpenRouter-style list or is empty. Regression for Pass-7 review finding
    that the duplicate-check had been validating against the resolved config
    result instead of the raw user intent."""

    async def test_direct_provider_anthropic_fallback_passes_quorum(self):
        import os as _os
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()

        # User has a non-matching OpenRouter-style reviewer list but only
        # Anthropic key is present. `config.get_review_models` will fall back
        # to `[main, light, light]`.
        env = {
            "OUROBOROS_REVIEW_MODELS": (
                "openai/gpt-5.5,google/gemini-3.1-pro-preview,"
                "anthropic/claude-opus-4.6"
            ),
            "OUROBOROS_MODEL": "anthropic::claude-opus-4-6",
            "OUROBOROS_MODEL_LIGHT": "anthropic::claude-sonnet-4-6",
            "OPENROUTER_API_KEY": "",
            "OPENAI_API_KEY": "",
            "OPENAI_BASE_URL": "",
            "OPENAI_COMPATIBLE_API_KEY": "",
            "CLOUDRU_FOUNDATION_MODELS_API_KEY": "",
            "ANTHROPIC_API_KEY": "sk-ant-test",
        }

        fallback_shape = [
            "anthropic::claude-opus-4-6",
            "anthropic::claude-sonnet-4-6",
            "anthropic::claude-sonnet-4-6",
        ]

        with (
            patch.dict(_os.environ, env, clear=False),
            patch.object(_cfg, "get_review_models", return_value=fallback_shape),
            patch.object(pr, "_get_review_models", return_value=fallback_shape),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertNotIn("at least 2 reviewer slots", result,
            f"fallback [main, light, light] was rejected as insufficient slots: {result[:300]}")
        self.assertNotIn("duplicate reviewer models", result,
            f"server-generated fallback duplicates tripped the "
            f"user-duplicate branch: {result[:300]}")

    async def test_direct_provider_fallback_in_raw_env_does_not_trip_duplicate_gate(self):
        """Real-world failure mode: `apply_runtime_provider_defaults` →
        `_normalize_direct_review_models` writes `[main, light, light]` into
        settings; `apply_settings_to_env` then copies that string into
        `OUROBOROS_REVIEW_MODELS`. On exclusive-direct-provider setups the
        raw env will therefore look like user-authored duplicates.
        `_run_plan_review_async` must not mis-reject this — duplicates in
        raw env are only user-authored when an exclusive direct provider
        is NOT active. Regression for v4.39.0 final-round review Critical #3.
        """
        import os as _os
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()

        # Exact shape `_normalize_direct_review_models` writes into settings
        # for an anthropic-only setup with the shipped defaults.
        fallback_env = (
            "anthropic::claude-opus-4-6,"
            "anthropic::claude-sonnet-4-6,"
            "anthropic::claude-sonnet-4-6"
        )
        fallback_shape = [
            "anthropic::claude-opus-4-6",
            "anthropic::claude-sonnet-4-6",
            "anthropic::claude-sonnet-4-6",
        ]

        env = {
            "OUROBOROS_REVIEW_MODELS": fallback_env,
            "OUROBOROS_MODEL": "anthropic::claude-opus-4-6",
            "OUROBOROS_MODEL_LIGHT": "anthropic::claude-sonnet-4-6",
            "OPENROUTER_API_KEY": "",
            "OPENAI_API_KEY": "",
            "OPENAI_BASE_URL": "",
            "OPENAI_COMPATIBLE_API_KEY": "",
            "CLOUDRU_FOUNDATION_MODELS_API_KEY": "",
            "ANTHROPIC_API_KEY": "sk-ant-test",
        }

        with (
            patch.dict(_os.environ, env, clear=False),
            patch.object(_cfg, "get_review_models", return_value=fallback_shape),
            patch.object(pr, "_get_review_models", return_value=fallback_shape),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertNotIn(
            "duplicate reviewer models", result,
            "Server-generated direct-provider fallback written into env "
            "must not be mis-flagged as user-authored duplicates. "
            f"Got: {result[:400]}",
        )
        self.assertNotIn("at least 2 reviewer slots", result)

    async def test_openrouter_user_authored_duplicates_are_slots(self):
        """OpenRouter duplicate entries are explicit reviewer slots."""
        import os as _os
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()

        env = {
            "OUROBOROS_REVIEW_MODELS": "openai/gpt-5.5,openai/gpt-5.5,anthropic/claude-opus-4.6",
            "OPENROUTER_API_KEY": "sk-or-test",
            "OPENAI_API_KEY": "",
            "ANTHROPIC_API_KEY": "",
        }

        with (
            patch.dict(_os.environ, env, clear=False),
            patch.object(_cfg, "get_review_models",
                         return_value=["openai/gpt-5.5", "openai/gpt-5.5",
                                       "anthropic/claude-opus-4.6"]),
            patch.object(pr, "_get_review_models",
                         return_value=["openai/gpt-5.5", "openai/gpt-5.5",
                                       "anthropic/claude-opus-4.6"]),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr,
                "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertNotIn("duplicate reviewer models", result)

    async def test_explicit_duplicates_under_direct_provider_are_slots(self):
        """Explicit duplicates under direct-provider setups are valid slots."""
        import os as _os
        from ouroboros.tools import plan_review as pr
        from ouroboros import config as _cfg

        ctx = _make_ctx()

        # User-authored duplicate list under an Anthropic-only setup.
        # The duplicate `anthropic::a` does NOT match the fallback shape
        # `[anthropic::claude-opus-4-6, anthropic::claude-sonnet-4-6,
        #  anthropic::claude-sonnet-4-6]` that
        # `direct_provider_review_models_fallback` would emit, so the gate
        # must still fire.
        user_duplicates = (
            "anthropic::claude-test-a,"
            "anthropic::claude-test-a,"
            "anthropic::claude-test-b"
        )
        env = {
            "OUROBOROS_REVIEW_MODELS": user_duplicates,
            "OUROBOROS_MODEL": "anthropic::claude-opus-4-6",
            "OUROBOROS_MODEL_LIGHT": "anthropic::claude-sonnet-4-6",
            "OPENROUTER_API_KEY": "",
            "OPENAI_API_KEY": "",
            "OPENAI_BASE_URL": "",
            "OPENAI_COMPATIBLE_API_KEY": "",
            "CLOUDRU_FOUNDATION_MODELS_API_KEY": "",
            "ANTHROPIC_API_KEY": "sk-ant-test",
        }

        with (
            patch.dict(_os.environ, env, clear=False),
            patch.object(_cfg, "get_review_models",
                         return_value=["anthropic::claude-test-a",
                                       "anthropic::claude-test-a",
                                       "anthropic::claude-test-b"]),
            patch.object(pr, "_get_review_models",
                         return_value=["anthropic::claude-test-a",
                                       "anthropic::claude-test-a",
                                       "anthropic::claude-test-b"]),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("ouroboros.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr,
                "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertNotIn("duplicate reviewer models", result)


if __name__ == "__main__":
    unittest.main()
